[package]
authors = ["Genna Wingert"]
categories = ["algorithms"]
description = "SPIR-V compiler for CubeCL"
edition.workspace = true
keywords = ["gpu", "compiler"]
license.workspace = true
name = "cubecl-spirv"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-spirv"
version.workspace = true

[features]
default = [
  "std",
  "cubecl-common/default",
  "cubecl-core/default",
  "cubecl-runtime/default",
]
std = ["cubecl-common/std", "cubecl-core/std", "cubecl-runtime/std"]

[dependencies]
bitflags = { workspace = true }
cubecl-common = { path = "../cubecl-common", version = "0.5.0", default-features = false }
cubecl-core = { path = "../cubecl-core", version = "0.5.0" }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.5.0", default-features = false, features = [
  "channel-mutex",
] }
half = { workspace = true }

hashbrown = { workspace = true }
# rspirv = "0.12"
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "267882d4e77a7457a1d87e3c8189f0d44e19e169" }
rspirv-ext = { git = "https://github.com/wingertge/rspirv-ext.git", rev = "991bf4b5d979554cc903ca6519fbb238beec21c7" }

# Optimizer
cubecl-opt = { path = "../cubecl-opt", version = "0.5.0" }
